### ISSUE TITLE
SketchyBar Installation Failure : Beginner Issue

### ISSUE THREAD

**Issue by ssl012** [slano-ls/SketchyBar#1]
Hi, I'm sorry for the question but I am new to sketchybar and MacOS. 
How can I install this so that it works on my MacOS

**Comment by slano-ls** [comment]
Hi no worries, next time if you have a question about something like this feel free to search it up on the *SKETCHYBAR* repository made by @felixkratz. 

First make sure that you have sketchybar installed, you can do this by doing `brew install sketchybar` after this, using the command `cd .config` in your terminal, you will reach the configuration section of your sketchybar, just use the command `mkdir sketchybar` to create your folder, and then copy and paste the files from my repo into that directory
